language: python
env:
        global:
                - CC_TEST_REPORTER_ID=afe02543b4c58c294ab40164bf63a43318c828fcb613b6056695e6ce0df3791a
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
script:
        - coverage run -m unittest discover --start-directory tests --top-level-directory . --verbose
        - coverage xml -o coverage.xml
        - bash <(curl -s https://codecov.io/bash)
after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug
notifications:
        slack: humancellatlas:BpnE92Kj26Xr0qRpNxZOkJa2
